/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * SpyLab
 * OpenAPI spec version: 0.1.0
 */
export interface AnalyzeBox {
  x: number;
  y: number;
  w: number;
  h: number;
  face_confidence: number;
  similar_faces: number;
}

export interface BodyAnalyzeImageApiAnalyzePost {
  file: Blob;
}

export interface BodyFindSimilarImageApiSimilarToImagePost {
  image: Blob;
  x: number;
  y: number;
  w: number;
  h: number;
}

export interface DashStats {
  face_count_total: number;
  face_count_24h: number;
  user_count_total: number;
}

export interface DetailData {
  data: FaceItemResponse;
  faces: FaceItemResponse[];
}

export interface FaceItemResponse {
  /** */
  id: number;
  fn: string;
  model: string;
  confidence: number;
  preview_path: string;
  source_filepath: string;
  x: number;
  y: number;
  w: number;
  h: number;
  preview_url: string;
  source_url: string;
}

export interface FaceSimilarItemResponse {
  /** */
  id: number;
  fn: string;
  model: string;
  confidence: number;
  preview_path: string;
  source_filepath: string;
  x: number;
  y: number;
  w: number;
  h: number;
  is_same: boolean;
  distance: number;
  preview_url: string;
  source_url: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface LoginResponse {
  token: string;
  token_type: "bearer";
}

export interface MeDto {
  id: number;
  email: string;
}

export interface UploadImageResponse {
  preview_url: string;
  source_url: string;
  boxes: AnalyzeBox[];
}

export interface UserItem {
  id: number;
  email: string;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type DetailImageApiDetailGetParams = {
  id: number;
};

export type ReadRandomApiListGetParams = {
  search?: string;
  limit?: number;
};

export type FindSimilarIdApiSimilarToIdGetParams = {
  id: number;
  model: string;
  metric?: string;
};

export type UserListApiUsersGetParams = {
  _start?: number;
  _end?: number;
};
